# SITE CONFIGURATION
title: Juliany Raiol # your site title
author: julianyraiol # You :P
description: > # Meta description of Homepage
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "https://julianyraiol.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Juliany Raiol
  links:
    - https://twitter.com/julianyraiol
    - https://www.facebook.com/julianyraiol
    - https://www.linkedin.com/in/julianyraiol
    - https://github.com/julianyraiol

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}

tagline: PyLady, Developer, Community and Open Data

profile_img: favicon.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: julianyraiol@gmail.com # email for form submission

twitter_username: julianyraiol # replace with your_twitter_username or comment to remove link from footer
github_username:  julianyraiol # replace with your_github_username or comment to remove link from footer
instagram_username: juliany.raiol # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: julianyraiol # to enable comments replace with your_disqus_shortname

google_tag_manager: UA-142700185-1 # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
