<<<<<<< HEAD
# SITE CONFIGURATION
title: Juliany Raiol # your site title
author: julianyraiol # You :P
description: É bacharela em Sistemas de Informação pela Universidade do Estado do Amazonas. Tem experiência com desenvolvimento Web/Mobile, Unity e Análise de Dados. 
Atualmente, trabalha como desenvolvedora de software na iTriad Pesquisa e Desenvolvimento.

url: "https://julianyraiol.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Juliany Raiol
  links:
    - https://twitter.com/julianyraiol
    - https://www.facebook.com/julianyraiol
    - https://www.linkedin.com/in/julianyraiol
    - https://github.com/julianyraiol

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Sobre', link: '/about'}

tagline: 

profile_img: favicon.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: julianyraiol@gmail.com # email for form submission

twitter_username: julianyraiol # replace with your_twitter_username or comment to remove link from footer
github_username:  julianyraiol # replace with your_github_username or comment to remove link from footer
instagram_username: juliany.raiol # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: julianyraiol # to enable comments replace with your_disqus_shortname

google_tag_manager: UA-142700185-1 # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
=======
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Your awesome title
email: julianyraiol@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: julianyraiol
github_username: julianyraiol

# Build settings
#theme: minima
theme: jekyll-theme-clean-blog

plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
>>>>>>> add new template
